### ISSUE TITLE
No plugins for HP Reverb G2 Omnicept Edition？

### ISSUE THREAD

**Issue by AbaiQi** [ghostiam/BrokenEye#10]
I use HP Reverb G2 Omnicept Edition and don't know how to use this.
The project only provides PimaxCrystalAdvanced plugin (without BrokenEye).

**Comment by ghostiam** [comment]
Even though the plugin has such a name, it works with any headset with Tobii tracking

**Comment by AbaiQi** [comment]
> Even though the plugin has such a name, it works with any headset with Tobii tracking

Thank you for your help.
