### ISSUE TITLE
What version of eyetrackVR was tested?

### ISSUE THREAD

**Issue by sveken** [ghostiam/BrokenEye#2]
Hello,
So i have this setup and im using branch.16 of the prerelease of eyetrackVR. 

What is happening is eyetrackVR will just stop updating from the camera feed. sometimes it happens in 30 seconds sometimes 2 minutes. This causes the openness to get stuck. simply going to settings and back to both eyes fixes it. 

I know its not a bug with "brokeneye" but i just wanted to know what version you are using/tried so i can rollback to that and try it. 
I know it states latest prerelease but i think its bugged.

thanks.

**Comment by ghostiam** [comment]
Hello, thanks for your interest in the project.

Try version [branch.11](https://github.com/EyeTrackVR/EyeTrackVR/releases/tag/v1.0.0-HSF-and-new-algos-feature-branch.11)

**Comment by ghostiam** [comment]
Hello, thanks for your interest in the project.

Try version [branch.11](https://github.com/EyeTrackVR/EyeTrackVR/releases/tag/v1.0.0-HSF-and-new-algos-feature-branch.11) or [branch.8](https://github.com/EyeTrackVR/EyeTrackVR/releases/tag/v1.0.0-HSF-and-new-algos-feature-branch.8)

**Comment by ghostiam** [comment]
Thanks for the info, I'll fix the README soon.
